---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: metabase-db-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: metabase-db-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      engineVersion: v2
      data:
        MB_DB_TYPE: postgres
        MB_DB_DBNAME: '{{ .dbname }}'
        MB_DB_HOST: '{{ index . "pgbouncer-host" }}'
        MB_DB_PORT: '{{ index . "pgbouncer-port" }}'
        MB_DB_USER: '{{ .user }}'
        MB_DB_PASS: '{{ .password }}'
        MB_DB_CONNECTION_URI: 'postgres://{{ .user }}:{{ .password }}@{{ index . "pgbouncer-host" }}:{{ index . "pgbouncer-port" }}/{{ .dbname }}?sslmode=require&pgbouncer=true'
  dataFrom:
  - extract:
      key: postgres-pguser-metabase
---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: metabase-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: metabase-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
  dataFrom:
  - extract:
      key: metabase

