---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-istio-ingress-any-user
  namespace: team-1-prod
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/istio-system/sa/istio-ingress
      when:
        - key: request.headers[kubeflow-userid]
          values: ["*"]


