---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubeflow-manifests
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/kubeflow/manifests
  ref:
    tag: v1.10.2
  ignore: |
    # exclude all
    /*
    # include example directory for deployment
    !/example

