apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: docker.io/kubeflownotebookswg/notebook-controller
  newName: docker.io/kubeflownotebookswg/notebook-controller
  newTag: v1.9.2
kind: Kustomization
resources:
- ../default
