---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actions-runner-controller.yaml
  - ./airbyte.yaml
  - ./authentik-charts.yaml
  - ./bitnami.yaml
  - ./backube.yaml
  - ./bjw-s.yaml
  - ./bytewax.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./coredns.yaml
  - ./crunchydata.yaml
  - ./dagster.yaml
  - ./dask.yaml
  - ./descheduler.yaml
  - ./dragonfly.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./flyte.yaml
  - ./grafana.yaml
  - ./growthbook.yaml
  - ./homepage.yaml
  - ./istio.yaml
  - ./ingress-nginx.yaml
  - ./intel.yaml
  - ./itzg.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-sigs-nfd.yaml
  - ./kubeflow-spark-operator.yaml
  - ./metrics-server.yaml
  - ./movetokube.yaml
  - ./node-feature-discovery.yaml
  - ./openebs.yaml
  - ./piraeus.yaml
  - ./postfinance.yaml
  - ./prefect.yaml
  - ./prometheus-community.yaml
  - ./ray.yaml
  - ./rook-ceph.yaml
  - ./runix.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./stevehipwell.yaml
  - ./tofu-controller.yaml
  - ./userinit-controller.yaml
  - ./weave-gitops.yaml
  - ./coder-charts.yaml
  - ./harbor.yaml
  - ./meilisearch.yaml
  - ./windmill.yaml
  - ./qdrant.yaml
  - ./tailscale.yaml
  - ./lightdash.yaml
  - ./redpanda.yaml
  - ./spark-operator.yaml
  - ./truecharts.yaml
  - ./nvidia-charts.yaml
  - ./seldonio.yaml
  - ./gitlab-charts.yaml
  - ./dify.yaml
  - ./argocd.yaml
