---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeflow-secrets
  namespace: flux-system
spec:
  targetNamespace: kubeflow
  commonMetadata:
    labels:
      app.kubernetes.io/name: kubeflow-secrets
  dependsOn:
    - name: external-secrets-stores
  path: ./kubernetes/apps/datasci/kubeflow-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m


