---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  # This Certificate is created by our earlier manual workaround as `kyverno-svc-tls`.
  # We keep the same name so cert-manager manages it consistently.
  name: kyverno-svc-tls
  namespace: kyverno
spec:
  # This is the Secret Kyverno uses for its webhook server TLS cert.
  secretName: kyverno-svc.kyverno.svc.kyverno-tls-pair
  issuerRef:
    name: kyverno-webhook-ca
    kind: Issuer
  commonName: kyverno-svc.kyverno.svc
  dnsNames:
    - kyverno-svc
    - kyverno-svc.kyverno
    - kyverno-svc.kyverno.svc
    - kyverno-svc.kyverno.svc.cluster.local

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kyverno-svc-serving-cert
  namespace: kyverno
spec:
  # This is the Secret Kyverno uses for its webhook server cert.
  secretName: kyverno-svc.kyverno.svc.kyverno-tls-pair
  issuerRef:
    name: kyverno-webhook-ca
    kind: Issuer
  commonName: kyverno-svc.kyverno.svc
  dnsNames:
    - kyverno-svc
    - kyverno-svc.kyverno
    - kyverno-svc.kyverno.svc
    - kyverno-svc.kyverno.svc.cluster.local


