---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  # This Certificate is created by our earlier manual workaround as `kyverno-svc-tls`.
  # We keep the same name so cert-manager manages it consistently.
  name: kyverno-svc-tls
  namespace: kyverno
spec:
  # This is the Secret Kyverno uses for its webhook server TLS cert.
  secretName: kyverno-svc.kyverno.svc.kyverno-tls-pair
  privateKey:
    algorithm: RSA
    size: 2048
    # Ensure a PKCS#1 key with correct PEM header ("BEGIN RSA PRIVATE KEY"),
    # because Kyverno's own generated CA key is PKCS#1.
    encoding: PKCS1
  issuerRef:
    name: kyverno-webhook-ca
    kind: Issuer
  commonName: kyverno-svc.kyverno.svc
  dnsNames:
    - kyverno-svc
    - kyverno-svc.kyverno
    - kyverno-svc.kyverno.svc
    - kyverno-svc.kyverno.svc.cluster.local
