---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeflow-oidc-authservice
  namespace: flux-system
spec:
  targetNamespace: istio-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: kubeflow-oidc-authservice
  dependsOn:
    - name: kubeflow-dex
    - name: istio-gateway
  path: ./common/oidc-client/oidc-authservice/overlays/ibm-storage-secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m

