---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeflow-pipelines-secrets
  namespace: flux-system
spec:
  targetNamespace: kubeflow
  commonMetadata:
    labels:
      app.kubernetes.io/name: kubeflow-pipelines-secrets
  dependsOn:
    - name: external-secrets-stores
    - name: kubeflow-namespace
  path: ./kubernetes/apps/datasci/kubeflow/pipelines/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeflow-pipelines
  namespace: flux-system
spec:
  targetNamespace: kubeflow
  commonMetadata:
    labels:
      app.kubernetes.io/name: kubeflow-pipelines
  dependsOn:
    - name: kubeflow-pipelines-secrets
    - name: kubeflow-pipelines-mysql
    - name: kubeflow-pipelines-argo-crds
    - name: kubeflow-profile-controller
    - name: kubeflow-istio-resources
  path: ./applications/pipeline/upstream/env/platform-agnostic-postgresql
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 15m
  patches:
    # Point to external Crunchy Postgres
    - patch: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: pipeline-install-config
        data:
          postgresHost: postgres-pgbouncer.database.svc.cluster.local
          postgresPort: "5432"
          pipelineDb: mlpipeline
          cacheDb: cachedb
          bucketName: kubeflow-pipelines
          mysqlHost: mysql
          mysqlPort: "3306"
      target:
        kind: ConfigMap
        name: pipeline-install-config
    # Update metadata postgres params
    - patch: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: metadata-postgres-db-parameters
        data:
          POSTGRES_HOST: postgres-pgbouncer.database.svc.cluster.local
          POSTGRES_PORT: "5432"
          POSTGRES_DBNAME: metadb
      target:
        kind: ConfigMap
        name: metadata-postgres-db-parameters
    # Scale down built-in Postgres to 0 (we use external)
    - patch: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: postgres
        spec:
          replicas: 0
      target:
        kind: Deployment
        name: postgres
    # Scale down metadata-postgres to 0 (we use external)
    - patch: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: metadata-postgres-db
        spec:
          replicas: 0
      target:
        kind: Deployment
        name: metadata-postgres-db
    # Scale down built-in MinIO to 0
    - patch: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: minio
        spec:
          replicas: 0
      target:
        kind: Deployment
        name: minio
    # Configure cache-server to use MySQL (doesn't support Postgres)
    - patch: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: cache-server
        spec:
          template:
            spec:
              containers:
                - name: server
                  env:
                    - name: DBCONFIG_DRIVER
                      value: "mysql"
                    - name: DBCONFIG_HOST_NAME
                      valueFrom:
                        configMapKeyRef:
                          key: mysqlHost
                          name: pipeline-install-config
                    - name: DBCONFIG_PORT
                      valueFrom:
                        configMapKeyRef:
                          key: mysqlPort
                          name: pipeline-install-config
                    - name: DBCONFIG_USER
                      valueFrom:
                        secretKeyRef:
                          key: username
                          name: mysql-secret
                    - name: DBCONFIG_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          key: password
                          name: mysql-secret
      target:
        kind: Deployment
        name: cache-server
    # Update postgres service to point to external Postgres
    - patch: |
        apiVersion: v1
        kind: Service
        metadata:
          name: postgres
        spec:
          type: ExternalName
          externalName: postgres-pgbouncer.database.svc.cluster.local
      target:
        kind: Service
        name: postgres
    # Update metadata-postgres service to point to external Postgres
    - patch: |
        apiVersion: v1
        kind: Service
        metadata:
          name: metadata-postgres-db
        spec:
          type: ExternalName
          externalName: postgres-pgbouncer.database.svc.cluster.local
      target:
        kind: Service
        name: metadata-postgres-db
    # Update MinIO service to point to external MinIO
    - patch: |
        apiVersion: v1
        kind: Service
        metadata:
          name: minio-service
        spec:
          type: ExternalName
          externalName: minio-secondary.storage.svc.cluster.local
      target:
        kind: Service
        name: minio-service
    # Increase ml-pipeline startup probe timeout (DB migrations can take time)
    - patch: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ml-pipeline
        spec:
          template:
            spec:
              containers:
                - name: ml-pipeline-api-server
                  startupProbe:
                    failureThreshold: 30
                    initialDelaySeconds: 30
                    periodSeconds: 10
      target:
        kind: Deployment
        name: ml-pipeline
    # Disable RBAC for metadata-grpc (allows metadata-writer to connect)
    - patch: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: metadata-grpc-deployment
        spec:
          template:
            spec:
              containers:
                - name: container
                  args:
                    - --grpc_port=$(METADATA_GRPC_SERVICE_PORT)
                    - --metadata_source_config_type=postgresql
                    - --postgres_config_host=$(MLMD_DB_HOST)
                    - --postgres_config_port=$(POSTGRES_PORT)
                    - --postgres_config_dbname=$(POSTGRES_DBNAME)
                    - --postgres_config_user=$(POSTGRES_USER)
                    - --postgres_config_password=$(POSTGRES_PASSWORD)
                    - --enable_database_upgrade=true
                    - --grpc_authorization_enabled=false
      target:
        kind: Deployment
        name: metadata-grpc-deployment
    # Fix cache-server webhook secret name
    - patch: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: cache-server
        spec:
          template:
            spec:
              volumes:
                - name: webhook-tls-certs
                  secret:
                    secretName: webhook-certs
      target:
        kind: Deployment
        name: cache-server
