---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeflow-pipelines
  namespace: flux-system
spec:
  targetNamespace: kubeflow
  commonMetadata:
    labels:
      app.kubernetes.io/name: kubeflow-pipelines
  dependsOn:
    - name: kubeflow-profile-controller
    - name: kubeflow-istio-resources
  path: ./applications/pipeline/upstream/env/platform-agnostic-multi-user
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 15m

