---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeflow-namespace
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: kubeflow-namespace
  dependsOn:
    - name: istio-istiod
  path: ./common/kubeflow-namespace/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m

