---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: cache-webhook-kubeflow
  annotations:
    # Inject CA bundle from the issued certificate
    cert-manager.io/inject-ca-from: kubeflow/cache-server-webhook
webhooks:
  - name: cache-server-webhook.kubeflow.svc
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 10
    failurePolicy: Fail
    clientConfig:
      service:
        name: cache-server
        namespace: kubeflow
        path: /mutate
        port: 443
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["argoproj.io"]
        apiVersions: ["*"]
        resources: ["workflows"]
        scope: "Namespaced"

