---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeflow-jupyter-web-app
  namespace: flux-system
spec:
  targetNamespace: kubeflow
  commonMetadata:
    labels:
      app.kubernetes.io/name: kubeflow-jupyter-web-app
  dependsOn:
    - name: kubeflow-notebook-controller
  path: ./apps/jupyter/jupyter-web-app/upstream/overlays/istio
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m

