---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeflow-knative-serving
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: kubeflow-knative-serving
  dependsOn:
    - name: kubeflow-cert-manager-issuer
    - name: istio-istiod
  path: ./common/knative/knative-serving/overlays/gateways
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 10m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeflow-knative-eventing
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: kubeflow-knative-eventing
  dependsOn:
    - name: kubeflow-knative-serving
  path: ./common/knative/knative-eventing/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 10m

