---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeflow-dex
  namespace: flux-system
spec:
  targetNamespace: auth
  commonMetadata:
    labels:
      app.kubernetes.io/name: kubeflow-dex
  dependsOn:
    - name: kubeflow-cert-manager-issuer
    - name: istio-istiod
  path: ./common/dex/overlays/oauth2-proxy
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m

