---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway.yaml
  - authz.yaml
  - referencegrant-deploykf-istio-gateway-cert.yaml
  - headscale-istio-envoyfilter.yaml
  - istio-gw-selfsigned-issuer.yaml
  - istio-gw-certificate.yaml
  - volsync-egress.yaml
