---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeflow-cert-manager-issuer
  namespace: flux-system
spec:
  targetNamespace: cert-manager
  commonMetadata:
    labels:
      app.kubernetes.io/name: kubeflow-cert-manager-issuer
  dependsOn:
    - name: cert-manager
  path: ./common/cert-manager/kubeflow-issuer/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m

