---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./nas-ingress.yaml
  #- ./mc-dns.yaml
  #- ./mesh-ingress.yaml
  #- ./portainer-ingress.yaml
  - ./tdarr-ingress.yaml
  - ./supermicro-ingress.yaml
  #- ./vpn-endpoint.yaml
