---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeflow-common
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: kubeflow
      app.kubernetes.io/part-of: kubeflow
  dependsOn:
    - name: cert-manager
    - name: istio-istiod
  path: ./kubernetes/apps/datasci/kubeflow/common-overlay
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 10m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeflow-apps
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: kubeflow
      app.kubernetes.io/part-of: kubeflow
  dependsOn:
    - name: kubeflow-common
  path: ./kubernetes/apps/datasci/kubeflow/apps-overlay
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 10m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
