---
apiVersion: v1
kind: Namespace
metadata:
  name: kubeflow
  labels:
    goldilocks.fairwinds.com/enabled: "true"
    istio-injection: enabled
    pod-security.kubernetes.io/enforce: privileged
  annotations:
    volsync.backube/privileged-movers: "true"

