---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: metadata-grpc-allow
  namespace: kubeflow
spec:
  action: ALLOW
  selector:
    matchLabels:
      component: metadata-grpc-server
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/kubeflow/sa/kubeflow-pipelines-metadata-writer
              - cluster.local/ns/kubeflow/sa/ml-pipeline
    - {}  # Allow all internal traffic within namespace

