---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./mariadb-secret.yaml
  - ./helmrelease.yaml
  - ./wings-externalsecret.yaml
  - ./wings-pvc.yaml
  - ./wings-configmap.yaml
  - ./wings-helmrelease.yaml
  - ../../../../templates/volsync
  # Note: DNS for Wings node is handled via LoadBalancer service annotation

