---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: pterodactyl-wings-node
spec:
  endpoints:
    - dnsName: "gameserver-node-01.${SECRET_DOMAIN}"
      recordType: A
      targets:
        - "192.168.50.191" # LoadBalancer IP - update if it changes

