---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeflow-profile-controller
  namespace: flux-system
spec:
  targetNamespace: kubeflow
  commonMetadata:
    labels:
      app.kubernetes.io/name: kubeflow-profile-controller
  dependsOn:
    - name: kubeflow-admission-webhook
    - name: kubeflow-istio-resources
  path: ./applications/profiles/upstream/overlays/kubeflow
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m

