# JSON Patch to replace Katib DB Manager env vars for Crunchy Postgres
- op: replace
  path: /spec/template/spec/containers/0/env
  value:
    - name: DB_NAME
      value: "postgres"
    - name: KATIB_POSTGRESQL_DB_HOST
      value: postgres-pgbouncer.database.svc.cluster.local
    - name: KATIB_POSTGRESQL_DB_PORT
      value: "5432"
    - name: KATIB_POSTGRESQL_DB_DATABASE
      value: katib
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: postgres-pguser-katib
          key: user
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-pguser-katib
          key: password
    - name: KATIB_POSTGRESQL_SSL_MODE
      value: "disable"
