apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
        - name: ml-pipeline
          env:
            # Postgres connection - using Crunchy Postgres
            - name: MYSQL_HOST
              value: postgres-pgbouncer.database.svc.cluster.local
            - name: MYSQL_PORT
              value: "5432"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-pguser-kubeflow-pipelines
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pguser-kubeflow-pipelines
                  key: password
            - name: MYSQL_DATABASE
              value: mlpipeline
          volumeMounts:
            - name: postgres-secret
              mountPath: /etc/secrets/postgres
              readOnly: true
      volumes:
        - name: postgres-secret
          secret:
            secretName: postgres-pguser-kubeflow-pipelines
