---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: kserve-models-web-app
  namespace: kubeflow
spec:
  gateways:
    - kubeflow/kubeflow-gateway
  hosts:
    - "*"
  http:
    - match:
        - uri:
            prefix: /_/kserve-endpoints/
      rewrite:
        uri: /
      route:
        - destination:
            host: kserve-models-web-app.kubeflow.svc.cluster.local
            port:
              number: 80
    - match:
        - uri:
            prefix: /kserve-endpoints/
      rewrite:
        uri: /
      route:
        - destination:
            host: kserve-models-web-app.kubeflow.svc.cluster.local
            port:
              number: 80
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: kserve-models-web-app
  namespace: kubeflow
spec:
  action: ALLOW
  selector:
    matchLabels:
      app: kserve
      app.kubernetes.io/component: kserve-models-web-app
      app.kubernetes.io/name: kserve
      kustomize.component: kserve-models-web-app
  rules:
    - {}
