apiVersion: v1
kind: Namespace
metadata:
  name: kubeflow-user-example-com
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-1
  labels:
    app.kubernetes.io/name: kubeflow-profile
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-1-prod
  labels:
    app.kubernetes.io/name: kubeflow-profile
