---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: jupyter-web-app-allow-istio-ingress
  namespace: kubeflow
spec:
  action: ALLOW
  selector:
    matchLabels:
      app: jupyter-web-app
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/istio-system/sa/istio-ingress
      to:
        - operation:
            ports: ["5000"]


