---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: jupyter-web-app-allow-istio-ingress
  namespace: kubeflow
spec:
  action: ALLOW
  selector:
    matchLabels:
      app: jupyter-web-app
  # Allow requests to reach the notebooks web app; auth is enforced at the deployKF gateway (oauth2-proxy ext_authz).
  rules:
    - {}


