---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeflow-pipelines-viewer-crd
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: kubeflow-pipelines-viewer-crd
  dependsOn:
    - name: kubeflow-namespace
  path: ./applications/pipeline/upstream/base/pipeline/cluster-scoped
  prune: false
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      # Only apply the viewer-crd.yaml, ignore other files
      # This is handled by Flux's resource filtering

