---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeflow-pipelines-viewer-crd
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: kubeflow-pipelines-viewer-crd
  dependsOn:
    - name: kubeflow-namespace
  path: ./applications/pipeline/upstream/base/pipeline/cluster-scoped
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubeflow-manifests
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  patches:
    # Only include the Viewer CRD, not other cluster-scoped resources
    - patch: |
        apiVersion: kustomize.config.k8s.io/v1beta1
        kind: Kustomization
        resources:
          - viewer-crd.yaml
      target:
        kind: Kustomization

