apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:b40QUKcpQJEJiP/70ZeC/2sm,iv:NDQdnhMPj+Jr2YibY8dINZjwfJba4tqJ752CXVdIXA8=,tag:0Eu2GZeXC52ONO+Il8DWsA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:sxpjpwpqti803e39eAcBtqs6b0dulHv0x7QGIJmFXU4Tvsgr,iv:Ft1rSlsHyaR+QrqIZriUn2IVwFeMb/y22Oy8jOgS4uE=,tag:v0AMZ7fNWIfTlj7Sqm8lJg==,type:str]
    CLUSTER_SECRET_CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:zpAr2ZyfvwJu7oGICispIF4vSVzZNDiMRJrlpUqn3SY=,iv:2MU+WUYws4LZT/99JDF8oQzRkG2q7tmS357rMbejbEg=,tag:rIpjPfKEUFx2M2ys3EP2rw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:druW1UUty0ytOiM=,iv:a5WQQKQoDcS0wD5NYN5j4Iat2qRpBIUD5+ScVe36YAM=,tag:uzCkxt+UkDxjUb44s/DCPw==,type:str]
    SECRET_SECONDARY_DOMAIN: ENC[AES256_GCM,data:Zvghc3+MzihtiarZYFJ0JCiwGGaQxie/Keqg,iv:WNVtBJjlw25i3lYqwDkNftRYGFv7roEAEWacg45PQLA=,tag:eHg/7beJ8ZsHAExSoYDXSQ==,type:str]
    K8S_GW: ENC[AES256_GCM,data:DmsDxJ3q0zuBaN0bBp8=,iv:Y/3ry025nHIuBtmEc0lZoogL0MwAoFTQs2eONYDKCgA=,tag:NOTUl03uV4PQmwFhGMT2tQ==,type:str]
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:PzNdvTTUiYuVv0CUCyVNkdPN1exp,iv:0BAlszNrE6rmLi/XinNMIV/AaKknXKHsiXZBu4RhWrg=,tag:8Aem0EHUkGSFRzBptpkVIg==,type:str]
    SVC_HOME_ASSISTANT_ADDR: ENC[AES256_GCM,data:3BmOkukbpYIbAirl/yo=,iv:NBgb9T9IVAAYmPcBuk7j3lL+UrsilaRAD/TjC6o0stg=,tag:3PqMM5ze7uSPskwOhUltzA==,type:str]
    SVC_PLEX_ADDR: ENC[AES256_GCM,data:pc9NR63UtTzXtc9h1YI=,iv:noBKO2CB1SV0wGw1F5fwcU3fKpA6qoVjyujpv06WCpY=,tag:KhVhTwIIteH2vDoDwl/mrQ==,type:str]
    SVC_SYNCTHING_ADDR: ENC[AES256_GCM,data:FINZR6H0GzERHtW5MgE=,iv:hle8Vt2jaLoduWlKpmCfavQM6L28u51qWTtnWkujjDY=,tag:LVvrCRS/BDvEmZjRlGGhEw==,type:str]
    SVC_MQTT_ADDR: ENC[AES256_GCM,data:+FVx780OlnZ6lDyMa9s=,iv:3Sfkaahr8FEubkSzjVYl+4n4suQN9c37rS2A7//VaXE=,tag:6yanwMjd50gH3YNhvLblDQ==,type:str]
    SVC_VECTOR_ADDR: ENC[AES256_GCM,data:MKIebgSIpSNVvCkicyM=,iv:DJciYFhUFRLrFbjYvX+FFzqLRXbuPNV9E+RlmwIUm5I=,tag:ntwBwYu0i9WikQxhrpccpg==,type:str]
    SVC_CPGO_ADDR: ENC[AES256_GCM,data:CgCOXDxC+669v8uJvXI=,iv:Qt6wTqKp4cVBIYtF7HeyMvEKdmcE+VnO9guBkil/q9E=,tag:9iV/ijvEoEl9EZTOVlTVig==,type:str]
    SECRET_NFS_DATA: ENC[AES256_GCM,data:F1lG/WqZXQ0A,iv:aEeYuhk8slh+QPHRTpogbl2FiwNwwo1DSk0UgJlBr6I=,tag:pytkXIq5hZJenfb/weWdNg==,type:str]
    SECRET_NFS_MINIO: ENC[AES256_GCM,data:9xAl3Gu3EpHxKRp1JppWNg==,iv:sYpIhMiunRJyDF5R3gN1bzVyO0jmGn2PMe6ajW8ccGw=,tag:e2XIWnEbQjKcbmXrqt/TEQ==,type:str]
    SECRET_NFS_POSTGRES: ENC[AES256_GCM,data:/2ElJHvg7T9X0yz7apwTp22BM9tpI0zJR5e0,iv:qMS5OQhDdlNjIS6gTAStCuFGmdy7WGa2QgGSyci020E=,tag:+Y8RNl7lT7KAIm1J6+A4QQ==,type:str]
    SECRET_NFS_SYNCTHING: ENC[AES256_GCM,data:y38gNRUGc8ffct69hWIol16zGQ==,iv:1a5FAF5FXmzl9ir2YLIMpOMaFtfzl2OGBM25q+L8YL4=,tag:QDeZ856g2ITnK8SjCmZgrw==,type:str]
    SECRET_NFS_PAPERLESS: ENC[AES256_GCM,data:ywGZK5lV7Dvr7Gjj5pAiluAZkA==,iv:KvVFRvrQCZgroQ5xQbEXiEnWhLxvZQMa4nG4I3dXXlw=,tag:D0FiAuA/ZruFOK/lMGkv8g==,type:str]
    MINIO_TOKEN: ENC[AES256_GCM,data:r0RcoFGvsuB49jhERtqy/2HGs7s=,iv:vmm8o9CmVQg9EIjvXHDUjJHW3++HGdheO5dMuuqWQZs=,tag:Q4Pgby4Mxhh1Lp8W7+xSUw==,type:str]
    NAS_IP: ENC[AES256_GCM,data:xjPaxGda0tVk2fZbuw==,iv:A60XzjnOcKKlruMLtHjtJFSl2/nOuywznSE5YqpqekA=,tag:K91SDnsJe9l4hyP4IzGhUg==,type:str]
    SUPERMICRO_IP: ENC[AES256_GCM,data:iuZXaOI4DkvH9DzFFg==,iv:d/y13qt7CxF94blcSahR9k2d5rgGn6mt1SVRSgY1Bn8=,tag:aGE5xvZ2B57OQsH9SbRtwQ==,type:str]
    UNIFI_CONTROLLER_IP: ENC[AES256_GCM,data:KKofh9kBJ0E0XDa5DmtrmvoIMA==,iv:jix59PuqClNEBTdoCKZudlyxJNnMRsx8prDDOikOGKY=,tag:VMRzMf+qrq/unj2+TwiGIw==,type:str]
    PLEX_TOKEN: ENC[AES256_GCM,data:fhZaqw4i+Bd0YSoq0RMUSFbcmaw=,iv:PqM9W8ZjVH0jHvHsZShY0uyPJ8gxtffz7VuI8Cuay6A=,tag:5VQWgf2Dc2BWfRKxyFCV5w==,type:str]
    LATITUDE: ENC[AES256_GCM,data:oFdd9Dlw1lwlurLje4gNYMc=,iv:szbDXHmZwppDgQzp/3gQPhDk0CtcIBpYRYhCFqH26Jg=,tag:dU6mT1LUvjDKfDC7suNVmw==,type:str]
    LONGITUDE: ENC[AES256_GCM,data:4aZ6O/HCRrAkL/ANYm4Pe5WH,iv:OS++Xo/qWld6fibzQoljBWL6lgQROOmY5+Vbt2ZUG34=,tag:IFjp8L57ZcT/58jaChBVwQ==,type:str]
    #ENC[AES256_GCM,data:klsdZ7pDo7+iW8nFzoOz9WfVadMdpT0=,iv:z6ZNXQv1oKiq20Y+CE6i2hFGNE7UPsqR3KUew0OAymU=,tag:Opp2BYwEGWjkyA0UrTb9TA==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15wktkwh8dgasswz9u04axxaa4edc88nld3ajldnr3mtgjfmfyqtqc0cu0k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSlVXSlJ3a1RlRldUNlFP
            RXVnUGFLcitlc0Rsa3Z4bXVhNlNHUTBTRHdNCk9zQ0ZOUGMxSWIvaG1JT1kvcFBG
            M09wamg1ZjBHZnRPekxxZVh1dGlyOEkKLS0tIEhHUnErNnlGSHl5NWhNZWFzeUNw
            anhDcTlibjBiN0p0TnRpR0RhQ3BSUFEKz2gQlq33nhX779htmPMuEcABsX/LAkrK
            tdOP6WQFO1zdXg6qlGG6FiZdgHfnM6plN5DBBgMZ9ZepzfroH1MRPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-23T11:44:34Z"
    mac: ENC[AES256_GCM,data:fNjyiWiHeiBjgkqhPN67N5fCXt7QWS7Q/4VSUzilji5l1uXNwrOE1kmaBo7SHwgu2uUoJ3cU7B9jQRuyjX0tdjI0iNkwuvZZ5K9XDk/guP3cO9lsva503Y2Q82OBmet3i1p2y0xNW6duYqSJfbAn91pdCTrZvD7z04Es2p8W1Ks=,iv:r/5cFVTPCsSpY4gNdYKnsMuRVH0eEFSixsDg9rQ63Bk=,tag:/HUYP4v8Y73nVeZL7MWxHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
