---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: katib-ui-deploykf
  namespace: kubeflow
spec:
  gateways:
    - istio-system/deploykf-gateway
  hosts:
    - deploykf.istio.local
  http:
    # Some dashboards link via the "proxy" style path `/_/katib/`
    - match:
        - uri:
            prefix: /_/katib/
      rewrite:
        uri: /katib/
      route:
        - destination:
            host: katib-ui.kubeflow.svc.cluster.local
            port:
              number: 80
    - match:
        - uri:
            prefix: /katib/
      rewrite:
        uri: /katib/
      route:
        - destination:
            host: katib-ui.kubeflow.svc.cluster.local
            port:
              number: 80


