---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: katib-ui-deploykf
  namespace: kubeflow
spec:
  gateways:
    - istio-system/deploykf-gateway
  hosts:
    - deploykf.istio.local
  http:
    - match:
        - uri:
            prefix: /katib/
      rewrite:
        uri: /katib/
      route:
        - destination:
            host: katib-ui.kubeflow.svc.cluster.local
            port:
              number: 80


