---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: seldon-controller-manager
  namespace: istio-system
spec:
  jobLabel: seldon-controller
  selector:
    matchLabels:
      control-plane: seldon-controller-manager
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: seldon-runtime
  namespace: istio-system
spec:
  jobLabel: seldon-runtime
  namespaceSelector:
    any: true
  selector:
    matchExpressions:
      - key: seldon-deployment-id
        operator: Exists
  podMetricsEndpoints:
    - port: metrics
      path: /prometheus
      interval: 30s
