---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: kubeflow
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        root_password: "{{ .password }}"
  dataFrom:
    - extract:
        key: postgres-pguser-kubeflow-pipelines
---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret-extended
  namespace: kubeflow
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: postgres-secret-extended
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        username: "{{ .user }}"
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: postgres-pguser-kubeflow-pipelines
---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mlpipeline-minio-artifact
  namespace: kubeflow
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: mlpipeline-minio-artifact
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        accesskey: "{{ .AWS_ACCESS_KEY_ID }}"
        secretkey: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: minio-secondary-creds
---
# MySQL secret (dummy - required by some components but we use Postgres)
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: kubeflow
type: Opaque
stringData:
  username: "unused"
  password: "unused"

