---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
# team-1 and team-1-prod removed (were from DeployKF)
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []


