apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airbyte
  namespace: airbyte
spec:
  interval: 5m
  chart:
    spec:
      chart: airbyte
      version: 1.9.2
      sourceRef:
        kind: HelmRepository
        name: airbyte
        namespace: flux-system
  install:
    timeout: 30m
    remediation:
      retries: 3
  upgrade:
    timeout: 30m
    remediation:
      retries: 3
  values:
    # https://artifacthub.io/packages/helm/airbyte/airbyte
    # https://github.com/airbytehq/airbyte-platform/blob/main/charts/airbyte/values.yaml
    global:
      airbyteUrl: https://airbyte.${SECRET_DOMAIN}
    # Ingress created via app/ingress.yaml (chart ingress not used)
    ingress:
      enabled: false
