---
apiVersion: kubeflow.org/v1
kind: Profile
metadata:
  name: team-1
spec:
  owner:
    kind: User
    name: admin@admin.com
  resourceQuotaSpec: {}
---
apiVersion: kubeflow.org/v1
kind: Profile
metadata:
  name: team-1-prod
spec:
  owner:
    kind: User
    name: admin@admin.com
  resourceQuotaSpec: {}
